name: compatibility_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  multi_select_flutter: ^4.1.3
  collection: ^1.18.0 # Utility functions for Dart collections
  provider: ^6.0.5 # Или последняя версия

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
